from dataclasses import dataclass, field
from typing import Dict, Any, Optional

@dataclass
class Response:
    """Represents a response generated by a node or the transport layer."""
    success: bool
    data: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize response to dictionary for network transport."""
        return {
            "success": self.success,
            "data": self.data,
            "error": self.error
        }
        
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Response":
        """Deserialize response from dictionary."""
        return cls(
            success=data["success"],
            data=data.get("data", {}),
            error=data.get("error")
        )
